### ISSUE TITLE
Why specific version of Moq?

### ISSUE THREAD

**Issue by JohnMarkHowell** [rowanmiller/EntityFramework.Testing#4]
I'm curious as to why I have to use a specific version of Moq when using these (EntityFramework.Testing and EntityFramework.Testing.Moq) libraries?   I seem to have to install Moq version 4.2.1402.2112 in order to get the tests to run successfully.  Is this intended?

JohnMarkHowell@Hotmail.com
@JohnMarkHowell

**Comment by scott-xu** [comment]
Fixed in my fork repo: https://github.com/scott-xu/EntityFramework.Testing/commit/f78580aa82213081f4d12afcf467b15acff052c0
Moq 4.2.1408.0717 and above is required as it starts **automatically add implemented interfaces to mock**
https://github.com/Moq/moq4/commit/4ade20b9e09c474d81fef44154ad140bde5c1ba1

**Comment by rowanmiller** [comment]
Hey,

Sorry about the uber slow response... I just realized I wasn't getting notifications for this repo...

The dependency is listed as 4.2.1402.2112 but NuGet treats that as the min version. Here is the log from the package being installed:
`Attempting to resolve dependency 'Moq (≥ 4.2.1402.2112)'.`

I just tested, and you can chose to upgrade to a later version of Moq and everything just works. I used the latest stable version when I tested (4.2.1409.1722).

~Rowan
